# Generated by Django 5.2.6 on 2025-10-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_student_score1_student_score2_alter_student_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='score1',
            new_name='ufli_score_1',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='score2',
            new_name='ufli_score_2',
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
