# Generated by Django 5.2.6 on 2025-10-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_score1_student_ufli_score_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='independent',
            field=models.BooleanField(default=False),
        ),
    ]
